# 以下を参考に拡張機能を入れた
# https://qiita.com/kawasukeeee/items/e0973f762e12aaa256e2

# sampleとしては、以下も参考になる
# https://github.com/JamesMessinger/swagger-suite/blob/master/samples/user-manager/users.yaml

# 上記は、別のところに書きたい
# --------------------------------------------------

swagger: "2.0"
info:
  description: "ワンちゃんワンチャンに関するAPIです。ユーザはログインした後、ワンちゃんの情報を取得します。"
  version: "1.0.0"
  title: "Dogs API"
#  termsOfService: "http://swagger.io/terms/"
#  contact:
#    email: "ken1shirakura@gmail.com"
#  license:
#    name: "Apache 2.0"
#    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: localhost3000
# 必要性検討

definitions:
  login:
    required: [userId, password]
    properties:
      userId:
        type: string
        minLength: 1
      password:
        type: string
        minLength: 1
# 最小桁数検討

paths:
  /dogs:
    get:
      summary: "ワンちゃん情報取得API"
      description: "ワンちゃん情報を返します"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "ケルベロス"

  /login/userId/{userId}/password/{password}:
    post:
      summary: "ログイン用API"
      description: "ログインを行います"
      responses:
        200:
          description: "成功時のレスポンス"
